language: java

jdk:
    - oraclejdk7

services:
    - mysql

before_install: 
    - mysql -uroot -e "grant all on ecomerce.* to root@localhost identified by "
    - mysql -uroot -e "drop database if exists ecomerce"
    - mysql -uroot -e "create database ecomerce"


after_success:
    - mvn jacoco:report coveralls:report